#############################################################################
# Makefile for building: ../../bin/app_release/metaplayer7.app/Contents/MacOS/metaplayer7
# Generated by qmake (3.1) (Qt 6.6.2)
# Project:  metaplayer7.pro
# Template: app
# Command: /usr/local/bin/qmake -o metaplayer7.xcodeproj/project.pbxproj metaplayer7.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

MOC       = /usr/local/share/qt/libexec/moc
UIC       = /usr/local/share/qt/libexec/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH       = -I. -I../../libmetartc7/src -I../../include -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/6.6.2_1/share/qt/mkspecs/macx-clang -F/usr/local/lib
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: moc_predefs.h moc_mainwindow.cpp moc_YangPlayWidget.cpp moc_YangYuvPlayWidget.cpp ui_mainwindow.h
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/share/qt/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++1z -Wall -Wextra -fPIC -dM -E -o moc_predefs.h /usr/local/share/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_YangPlayWidget.cpp moc_YangYuvPlayWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_YangPlayWidget.cpp moc_YangYuvPlayWidget.cpp
moc_mainwindow.cpp: mainwindow.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QMainWindow \
		video/yangrecordthread.h \
		/usr/local/lib/QtCore.framework/Headers/QThread \
		/usr/local/lib/QtCore.framework/Headers/QVector \
		../../include/yangutil/buffer/YangVideoBuffer.h \
		yangplayer/YangYuvPlayWidget.h \
		/usr/local/lib/QtGui.framework/Headers/QOpenGLFunctions \
		yangplayer/YangPlayWidget.h \
		../../include/yangstream/YangSynBuffer.h \
		../../include/yangplayer/YangPlayerHandle.h \
		../../include/yangstream/YangStreamType.h \
		../../include/yangutil/yangavinfotype.h \
		../../include/yangutil/sys/YangSysMessageI.h \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/aiven/work/project/framework/metaRTC/demo/metaplayer7/moc_predefs.h -I/usr/local/Cellar/qt/6.6.2_1/share/qt/mkspecs/macx-clang -I/Users/aiven/work/project/framework/metaRTC/demo/metaplayer7 -I/Users/aiven/work/project/framework/metaRTC/libmetartc7/src -I/Users/aiven/work/project/framework/metaRTC/include -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/lib mainwindow.h -o moc_mainwindow.cpp

moc_YangPlayWidget.cpp: yangplayer/YangPlayWidget.h \
		/usr/local/lib/QtGui.framework/Headers/QOpenGLFunctions \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/aiven/work/project/framework/metaRTC/demo/metaplayer7/moc_predefs.h -I/usr/local/Cellar/qt/6.6.2_1/share/qt/mkspecs/macx-clang -I/Users/aiven/work/project/framework/metaRTC/demo/metaplayer7 -I/Users/aiven/work/project/framework/metaRTC/libmetartc7/src -I/Users/aiven/work/project/framework/metaRTC/include -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/lib yangplayer/YangPlayWidget.h -o moc_YangPlayWidget.cpp

moc_YangYuvPlayWidget.cpp: yangplayer/YangYuvPlayWidget.h \
		/usr/local/lib/QtGui.framework/Headers/QOpenGLFunctions \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/aiven/work/project/framework/metaRTC/demo/metaplayer7/moc_predefs.h -I/usr/local/Cellar/qt/6.6.2_1/share/qt/mkspecs/macx-clang -I/Users/aiven/work/project/framework/metaRTC/demo/metaplayer7 -I/Users/aiven/work/project/framework/metaRTC/libmetartc7/src -I/Users/aiven/work/project/framework/metaRTC/include -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/lib yangplayer/YangYuvPlayWidget.h -o moc_YangYuvPlayWidget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/usr/local/share/qt/libexec/uic
	/usr/local/share/qt/libexec/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

