# 文件列表按正则表达式排除,list(FILTER 实现, 3.5版本没有list(FILTER功能.
macro(list_excluding srcs)
    foreach(regex ${ARGN})
        unset(del_list)
        foreach(row ${${srcs}})
            string(REGEX MATCH ${regex} tmp1 ${row})
            if(tmp1)
                list(APPEND del_list ${row})
            endif()
        endforeach()
        foreach(row ${del_list})
            list(REMOVE_ITEM ${srcs} ${row})
        endforeach()
    endforeach()
endmacro()
